
[blockchain_a]
  type = "anvil"
  docker_cmd_params = ["-b", "5"]

[jd]
  # change to your version
  image = "jd-test-1:latest"

[price_provider]
  # without 0x prefix!
  feed_id = "018bfe8840700040000000000000000000000000000000000000000000000000"
  # used only if [data_source_config.fake] is not present
  # url = "api.real-time-reserves.verinumus.io/v1/chainlink/proof-of-reserves/TrueUSD"

  [price_provider.fake]
    port = 8171
    prices = [182.9, 162.71, 172.02]

[workflow_config]
	don_id = 1
	workflow_name = "abcdefgasd"

  use_cre_cli = true
  should_compile_new_workflow = false
  workflow_folder_location = "path-to-folder-with-main.go-of-your-workflow"

  [workflow_config.dependencies]
  capabilities_version = "v1.0.0-alpha"
  cre_cli_version = "v0.0.2"

  [workflow_config.compiled_config]
    binary_url = "https://gist.githubusercontent.com/Tofel/a91a240f16bb64bd1be44c93a38e6703/raw/cb7b2a56b37e333fe0bdce07b79538c4ce332f5f/binary.wasm.br"
    config_url = "https://gist.githubusercontent.com/Tofel/27c96141aac0c6eac832660c2abea6d4/raw/c8a3776ac34d484b81374bec01926619e1f54757/config.json2739136466"

[nodeset]
  nodes = 5
  override_mode = "each"

[nodeset.db]
  image = "postgres:15.6"

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      docker_ctx = "../../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      capabilities = ["./amd64_cron"]
      docker_ctx = "../../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      capabilities = ["./amd64_cron"]
      docker_ctx = "../../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      capabilities = ["./amd64_cron"]
      docker_ctx = "../../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """

  [[nodeset.node_specs]]

    [nodeset.node_specs.node]
      capabilities = ["./amd64_cron"]
      docker_ctx = "../../.."
      docker_file = "plugins/chainlink.Dockerfile"
      user_config_overrides = """
      [Feature]
			LogPoller = true

			[OCR2]
			Enabled = true
			DatabaseTimeout = '1s'

			[P2P.V2]
			Enabled = true
			ListenAddresses = ['0.0.0.0:5001']
      """
